apiVersion: apps/v1
kind: Deployment
metadata:
  name: pbwn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pbwn
  template:
    metadata:
      labels:
        app: pbwn
    spec:
      containers:
        - name: pbwn-container
          image: asia-east1-docker.pkg.dev/my-public-witnessing/my-docker-repo/pbwn-image
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: pbwn-service
spec:
  selector:
    app: pbwn
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
